### ISSUE TITLE
Function.prototype.toString requires that 'this' be a Function

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer-vm#1210]
![image](https://user-images.githubusercontent.com/1360552/99809957-1b49ca00-2b54-11eb-896a-7c6490d8efa8.png)

![image](https://user-images.githubusercontent.com/1360552/99810035-33b9e480-2b54-11eb-8018-f69ed161a9d1.png)

![image](https://user-images.githubusercontent.com/1360552/99810785-484aac80-2b55-11eb-81f2-aa0ca6ac012c.png)

![image](https://user-images.githubusercontent.com/1360552/99810828-5a2c4f80-2b55-11eb-991b-a95416006829.png)

In tests we have objects, like:

![image](https://user-images.githubusercontent.com/1360552/99810894-716b3d00-2b55-11eb-98ed-890de492f44f.png)

looks like we could check for constructor descriptor (should be non-enumerable)

@glimmer/utils

**Comment by rwjblue** [comment]
Hmm, it seems fairly odd to use a constructor property as something _other_ than a normal constructor function. 🤔

**Comment by rwjblue** [comment]
Since this is for debugging purposes though, it seems fine to double check that we have a function in `getFunctionName`. That might avoid the error, but it won't give you good/useful informational output from `getObjectName`.

Mind sending a PR to ensure we either only call `getFunctionName` with a function or have `getFunctionName` noop when it wasn't given a function?

**Comment by lifeart** [comment]
`Hmm, it seems fairly odd to use a constructor property as something other than a normal constructor function. 🤔`, agree, but it's simpliest way to get e-data model name :/
