### ISSUE TITLE
CJS compatibility dropped for `@glimmer/syntax` - intentional?

### ISSUE THREAD

**Issue by davidtaylorhq** [glimmerjs/glimmer-vm#1668]
Since https://github.com/glimmerjs/glimmer-vm/commit/57e59c4bcbdd06477170bc8e51ab02aeda7706b4, `@glimmer/syntax` is no longer including cjs modules in the published package.  Was this an intentional breaking change?

For context: we use `@glimmer/syntax` directly to power a [custom babel plugin](https://github.com/discourse/discourse/blob/e6fdfcdcd25d4bf7f009079cace41d0e9ffe4791/app/assets/javascripts/discourse-widget-hbs/lib/widget-hbs-compiler.js#L280), which is then consumed by ember-cli/embroider, which [seem to only support cjs babel plugins](https://github.com/embroider-build/embroider/blob/0aa8fc682d56a99d0305534ca7a00d165ad27019/packages/core/src/portable.ts#L223).

**Comment by jakebailey** [comment]
The dropping of CJS stuff has also broken DefinitelyTyped's `@types/ember__helper` package, which depends on `@glimmer/manager` and `@glimmer/runtime`. Though, `@ember/helper` is confusingly internal so it's hard to say if that's a problem or not. (Certainly a problem for keeping DT green.)

**Comment by NullVoxPopuli** [comment]
the DT types should use older copies of the glimmer dependencies -- we can't support DT types forever -- and I'm not actually sure even if we support them now -- feels kinda like a "Best effort" thing.

`@glimmer/syntax` absolutely should have a CJS option for stuff like what @davidtaylorhq mentioned, but also prettier.

I'll PR the re-adding CJS for just `@glimmer/syntax`.
We don't want to support CJS for all the packages though, because CJS is a huge pain, and since the VM is primarily something for browsers, it doesn't make much sense to emit CJS.

**Comment by mansona** [comment]
@davidtaylorhq for the record Embroider main (i.e. vite/unstable) will support esm plugins https://github.com/embroider-build/embroider/pull/2178

That PR even added a regression test so we won't backslide

**Comment by jakebailey** [comment]
I can prevent the DT package from pulling in 0.93 to get CI green, but I am a little confused as I thought glimmer and ember were under the same umbrella. I don't have enough context to understand what the private package `@ember/helpers` needs (and I don't really know why it was added to DT at all).

**Comment by NullVoxPopuli** [comment]
The DT packages are not under ember really -- moreso a community best effort :muscle: 
internal to ember, it depends on a bunch of things from the glimmer packages, so the DT types try to do the same (which is the better thing to do, usually) -- but the glimmer packages currently don't have semver guarantees due to all mostly being privateish packages

**Comment by NullVoxPopuli** [comment]
Just got around to poking at this, and it looks like CJS is already bundled:

![image](https://github.com/user-attachments/assets/ba8cd9ca-3180-4c36-abd2-70c9bda121a6)
![image](https://github.com/user-attachments/assets/dd1465af-8058-454d-9cdb-0eb41bc9216d)


🤔

**Comment by jakebailey** [comment]
Yeah, it's just locked off in a development condition which won't be applied by anyone; the same is true for the packages I mentioned. I'm not sure what the difference is, though, to know everything would be solved by pointing CJS to that dir unconditionally. (Or, maybe shipping the dev dir is a mistake)

**Comment by NullVoxPopuli** [comment]
well, where this is annoying is that ember uses require to try to point at ESM. but... ember is probably in the wrong here -- and it had some build improvements recently, so if it's not already fixed, it's probably something that I need to update in ember so that problem stops coming up 🙈

**Comment by NullVoxPopuli** [comment]
looks like only 3 deps need updating:
- `@glimmer/syntax`
- `@glimmer/util`
- `@glimmer/wire-format`

**Comment by jakebailey** [comment]
FWIW I sent https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71275, but then found https://github.com/emberjs/ember.js/blob/main/packages/%40ember/helper/package.json?rgh-link-date=2024-11-27T18%3A43%3A53Z which actually _is_ a module, but is also in TS, so I am in general, confused as to what's going on with all of this (I don't understand why any of this was on DT as it's private, why ember isn't at least pushing its types over to DT or something to match with the private package)

**Comment by NullVoxPopuli** [comment]
well, maybe the situation will improve in that DT PR after: https://github.com/glimmerjs/glimmer-vm/pull/1669 is released

**Comment by jakebailey** [comment]
It wouldn't improve unless `manager` and `runtime` are also changed; it does seem like this could be applied across all of the packages?

**Comment by NullVoxPopuli** [comment]
manager and runtime are not used in any cjs tooling.

for compatibility with DT, your tsconfig (and their tsconfigs) should probably try using `moduleResolution` bundler, or `node16` or something like that

**Comment by jakebailey** [comment]
> for compatibility with DT, your tsconfig (and their tsconfigs) should probably try using `moduleResolution` bundler, or `node16` or something like that (please let me know if this is a terrible idea 🙈 )

`bundler` is an illegal option on DT, but we have been considering allowing it for packages that should only ever be bundled.

`node16` would work, but only if i make `@ember/helpers` be `"type": "module"`, in which case I don't need glimmer to change anything at all. That actually seems right, given the package.json I linked to says `"type": "module"`, it's just that I didn't find it until just now. The disconnect between DT and ember here is a challenge.

The main thing I'm not sure of is the version number this ember package is supposed to have, since there is no npm entry to tell me what the current version is to then put on DT.
