### ISSUE TITLE
Create Templated DOM Class

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer-vm#492]
In #474 I started to unify and the APIs to do DOM creation and manipulation. This worked by down/up casting types where it was necessary. While this works we should be able to unify this further by creating a templated class. Conversation with @krisselden.

```
[3:36]  We maybe should have used generics to preserve the real dom  through places that just use simple dom

[3:36] 
That's the correct way

[3:37] 
`T extends Simple.Document`
```

**Comment by chancancode** [comment]
The specific strategy in here doesn't work anymore, because `Simple.DOM` types are no longer a strict super type of TypeScript's built-in DOM typings (mostly due to silly differences, arguably bugs, in the TS version). Also adding generics like that is very expensive as they proliferate virally and TS makes you repeat them a lot. We decided the soundless tradeoff is worth it in the case of simple vs real DOM and it should be rare anyway. Closing this in favor of #1076 which captures the intent/spirit of this original issue.
