### ISSUE TITLE
Preserve ordering of attributes, modifiers, and comments on Element Nodes for Pretty Printing

### ISSUE THREAD

**Issue by robert-j-webb** [glimmerjs/glimmer-vm#758]
The glimmer vm clobbers the order of attributes/modifiers/comments. See an example of this here: [Gist](https://astexplorer.net/#/gist/bca2f4aa4e311e0526f41f944e8535da/ec109efc4558aa695b57afb9b12b0107ad685e01)

Would you like it if I started working on a PR to fix this? 

cc @mmun

**Comment by mmun** [comment]
So I think ideally we would have

```
Attributes = (Attribute | Modifier | Comment)[]
```

sort of like how `{ x: 1, ...y }` in JavaScript parses to a Property and a SpreadProperty: https://astexplorer.net/#/gist/49d4853566c519d19b6c84c8f434c6de/5ad7b63b2ad7ddcc7751f60f9d0376395ef5e8c2

We may want to preserve the existing AST structure for now and add some extra data to the existing nodes so that you can recover the original order, e.g. putting a private `_index` on each of the nodes.

**Comment by Turbo87** [comment]
I don't think the printer in `glimmer-vm` needs to keep the order exactly the same. If you want to keep the template formatting the same then you should use the printer from https://github.com/ember-template-lint/ember-template-recast which aims to do exactly that.
